<% @base = "dc=test,dc=com" %>

authorizations: &AUTHORIZATIONS
  ## Authorization
  group_base: <%= "ou=groups,#{@base}" %>
  required_groups:
    - cn=admins,<%= "ou=groups,#{@base}" %>
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: blogAdmin
    
test: &TEST
  host: <%= "localhost" %>
  port: 3389
  attribute: cn
  base: <%= "ou=people,#{@base}" %>
  admin_user: <%= "cn=admin,#{@base}" %>
  admin_password: secret
  ssl: false
  <<: *AUTHORIZATIONS
  
development:
  <<: *TEST
