authorizations: &AUTHORIZATIONS
  ## Authorization
  group_base: ou=groups,dc=test,dc=com
  required_groups:
    - cn=admins,ou=groups,dc=test,dc=com
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: blogAdmin
    
test: &TEST
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: secret
  ssl: true
  <<: *AUTHORIZATIONS
  
development:
  <<: *TEST
