# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_imapable}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Kalderimis"]
  s.date = %q{2010-04-08}
  s.description = %q{For when you don't have access to LDAP}
  s.email = %q{josh.kalderimis@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "devise_imapable.gemspec",
     "lib/devise_imapable.rb",
     "lib/devise_imapable/imap_adapter.rb",
     "lib/devise_imapable/model.rb",
     "lib/devise_imapable/routes.rb",
     "lib/devise_imapable/schema.rb",
     "lib/devise_imapable/strategy.rb",
     "rails/init.rb",
     "test/devise_imapable_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshk/devise_imapable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Devise Imap authentication module}
  s.test_files = [
    "test/devise_imapable_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, ["> 1.0.4"])
    else
      s.add_dependency(%q<devise>, ["> 1.0.4"])
    end
  else
    s.add_dependency(%q<devise>, ["> 1.0.4"])
  end
end

