# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_ldap_authenticatable}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Curtis Schiewek"]
  s.date = %q{2010-07-22}
  s.description = %q{LDAP authentication module for Devise}
  s.email = %q{curtis.schiewek@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "devise_ldap_authenticatable.gemspec",
     "lib/devise_ldap_authenticatable.rb",
     "lib/devise_ldap_authenticatable/ldap_adapter.rb",
     "lib/devise_ldap_authenticatable/model.rb",
     "lib/devise_ldap_authenticatable/routes.rb",
     "lib/devise_ldap_authenticatable/schema.rb",
     "lib/devise_ldap_authenticatable/strategy.rb",
     "rails/init.rb",
     "test/devise_ldap_authenticatable_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/cschiewek/devise_ldap_authenticatable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{LDAP authentication module for Devise}
  s.test_files = [
    "test/devise_ldap_authenticatable_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, ["> 1.0.4"])
      s.add_runtime_dependency(%q<net-ldap>, [">= 0.0.0"])
    else
      s.add_dependency(%q<devise>, ["> 1.0.4"])
      s.add_dependency(%q<net-ldap>, [">= 0.0.0"])
    end
  else
    s.add_dependency(%q<devise>, ["> 1.0.4"])
    s.add_dependency(%q<net-ldap>, [">= 0.0.0"])
  end
end

