source 'http://rubygems.org'

gem 'rails', '3.0.0.beta4'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem "devise", "1.1.rc2"
gem "devise_ldap_authenticatable", :path => "../../"

group :test do
  gem "mocha"
  gem "shoulda"
  gem "autotest-rails"
  gem "ZenTest"
  gem "factory_girl"
end
