#!/usr/bin/env ruby

require 'erb'

## For OSX:
ENV['PATH'] = "#{ENV['PATH']}:/usr/libexec"

def file(n)
  File.read(File.expand_path(n, File.dirname(__FILE__)))
end

template = file('slapd-test.conf.erb')
normal_out = File.expand_path('slapd-test.conf', File.dirname(__FILE__))
ssl_out = File.expand_path('slapd-ssl-test.conf', File.dirname(__FILE__))

@conf_root = File.expand_path(File.dirname(__FILE__))
File.open(normal_out, 'w') do |f|
  @ssl = false
  f.write ERB.new(template).result(binding)
end
File.open(ssl_out, 'w') do |f|
  @ssl = true
  f.write ERB.new(template).result(binding)
end

if ARGV.first == '--ssl'
  exec "slapd -d 1 -f #{ssl_out} -h ldaps://localhost:3389"
else
  exec "slapd -d 1 -f #{normal_out} -h ldap://localhost:3389"
end
