#!/usr/bin/env ruby

## For OSX:
ENV['PATH'] = "#{ENV['PATH']}:/usr/libexec"

if ARGV.first == '--ssl'
  exec "slapd -d 1 -f slapd-ssl-test.conf -h ldaps://localhost:3389"
else
  exec "slapd -d 1 -f slapd-test.conf -h ldap://localhost:3389"
end
